// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZbrvaGGUMz-WgvslVMei4Xw5lG_PE20',
    appId: '1:685986294243:web:ef688b4270e1b3d536d8d6',
    messagingSenderId: '685986294243',
    projectId: 'map1-e6572',
    authDomain: 'map1-e6572.firebaseapp.com',
    storageBucket: 'map1-e6572.firebasestorage.app',
    measurementId: 'G-DVLLE1PME6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9HOJyRtCB7FGUATYu59QwTRSVjeyAyQc',
    appId: '1:685986294243:android:b77b4b11890dab6236d8d6',
    messagingSenderId: '685986294243',
    projectId: 'map1-e6572',
    storageBucket: 'map1-e6572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9wSCaLQZFixMxkmwYrdlRvjwV1D3lII',
    appId: '1:685986294243:ios:049750344ad478d336d8d6',
    messagingSenderId: '685986294243',
    projectId: 'map1-e6572',
    storageBucket: 'map1-e6572.firebasestorage.app',
    iosBundleId: 'com.example.map',
  );
}
